# Generated by Django 3.1.2 on 2020-10-02 18:36

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email_add', models.EmailField(max_length=254)),
                ('phonenum', phonenumber_field.modelfields.PhoneNumberField(default=0, max_length=128, region=None)),
                ('position', models.CharField(max_length=255)),
                ('education', models.CharField(max_length=255)),
                ('work_exp', models.FloatField()),
                ('resume', models.FileField(upload_to='static/')),
                ('video_resume', models.FileField(upload_to='media/')),
            ],
            options={
                'unique_together': {('email_add', 'phonenum')},
            },
        ),
    ]
