# Generated by Django 3.1.2 on 2020-10-02 18:42

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
        migrations.AlterUniqueTogether(
            name='userinfo',
            unique_together={('email_add', 'phone')},
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='phonenum',
        ),
    ]
