# Generated by Django 3.1.2 on 2020-10-02 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0002_auto_20201003_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='email_add',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='userinfo',
            unique_together=set(),
        ),
    ]
